"""create tables

Revision ID: 180512ae7fdd
Revises: 0bdf6da10cae
Create Date: 2025-02-24 16:26:40.385195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '180512ae7fdd'
down_revision: Union[str, None] = '0bdf6da10cae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database_creds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('db_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_database_creds_id'), 'database_creds', ['id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_path', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'SYNCING', 'PROCESSED', 'DELETED', name='filestatus'), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('date_modified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_full_path'), 'files', ['full_path'], unique=True)
    op.create_index(op.f('ix_files_status'), 'files', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_status'), table_name='files')
    op.drop_index(op.f('ix_files_full_path'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_database_creds_id'), table_name='database_creds')
    op.drop_table('database_creds')
    # ### end Alembic commands ###
