name: Lint and Test
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install poetry
      - run: poetry install --with dev
      - run: poetry run black --check .
      - run: poetry run ruff check .
      - run: poetry run mypy .
      - run: poetry run pytest
